### ISSUE TITLE
pls open pls

### ISSUE THREAD

**Issue by theprogrammingking** [vrrao01/team_meet#21]
excuse me did you use firebase or something llike mongodb or sql i need this for a project and the people section how to remove and can you put the invite to team link function that will be good and the jitsi meet logo changed to mine? isf you help me on this believe me ill be the happiest person in the world.

thanks,
folker

**Comment by vrrao01** [comment]
Hey @theprogrammingking, 
You can check out the documentation [here](https://github.com/vrrao01/team_meet/blob/main/Documentation.pdf) for the implementation details. ChatEngine is fully customisable and the people section can be removed. You can find more about the components [here](https://chatengine.io/docs/components). 
To replace the Jitsi logo you'll have to host your own instance of the Jitsi Meet server and make changes on some of the config files.
